Repository axielroque/child-theme, pull requests merged in 2023-10, with the labels that each got.

#11 Footer site
  assets/css/styles.css
  blocks-acf/acf/fields/footer-acf.php
  blocks-acf/config.php
  blocks-acf/functions/options-page.php
  dist/main.css
  footer.php
  tailwind.config.js
  template-parts/footer/footer-c2-widgets.php
  template-parts/footer/footer-c3-widgets.php
  template-parts/footer/footer-c4-widgets.php
  template-parts/footer/footer-widgets.php
Labels: enhancement

#16 Issue theme coding standards
  .gitignore
  blocks-acf/acf/acf-register-block.php
  blocks-acf/acf/blocks/hero.php
  blocks-acf/acf/blocks/testimonials.php
  blocks-acf/acf/blocks/timeline.php
  blocks-acf/acf/fields/fields.php
  blocks-acf/acf/fields/footer-acf.php
  blocks-acf/acf/fields/hero-fields.php
  blocks-acf/acf/fields/testimonials.php
  blocks-acf/acf/fields/timeline-fields.php
  blocks-acf/config.php
  blocks-acf/functions/options-page.php
  blocks-acf/templates-blocks/block-template-loader.php
  blocks-acf/templates-blocks/hero/index.php
  blocks-acf/templates-blocks/testimonials/index.php
  blocks-acf/templates-blocks/timeline/index.php
  composer.json
  composer.lock
  footer.php
  functions.php
  home.php
  inc/vite.php
  phpcs.xml.dist
  readme.md
  style.css
  template-parts/footer/footer-c2-widgets.php
  template-parts/footer/footer-c3-widgets.php
  template-parts/footer/footer-c4-widgets.php
  template-parts/footer/footer-widgets.php
Labels: enhancement, hactoberfest, HACKTOBERFEST-ACCEPTED

#15 Create main.yml
  .github/workflows/main.yml
Labels: enhancement, hactoberfest, HACKTOBERFEST-ACCEPTED

#17 update: add PHP check to readme.md
  readme.md
Labels: hactoberfest, HACKTOBERFEST-ACCEPTED
